language: ruby
rvm:
  - 2.1.3
branches:
  only:
    - master
cache: bundler
before_script:
  - cp config/database.yml.travis-ci config/database.yml
  - bundle exec rake db:create:all
  - bundle exec rake db:schema:load
